apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: korn-secrets-recv
  namespace: korn
spec:
  encryptedData:
    mq_pass: AgBnvZqhYTZppQtQ5PocdKibHMNoOcgzrq9ZK+dRBvPaHF2Pcfl/SLMKqejrXEsncFiwutmdmKVyzv1ej64G9ETORfpccbXgf5p3BqcLCS7HI064c1qRmoJiFhPXE+p3ABv7Zlx2JGxQEfHp51dN9M3m4u9tku5zn8dJ1LcLtyqSYEVMOTxlORC0PDEyPmMSYKGUhBYw8fnz4kEDEH6z9ZbtTdW2ZFRE0/BdaaJbjTSqXu5SdoCeU0TZzwkheb1/FdM/aY8yI//ySX3ufAuCLq4N2GIhoFpZHOMRKjx+HWROSKPuHqfyxFJSVTR8l9SPqwR6zB4qIup8D3vsEkMqhBMtLeNZJRqQtbToiwRSyhuLQOUkl9HgvsHNibgVCIO75TSv9EE6bWbSH8gBE5VBnQr2/qYwsoh6KU/pG8M+g55TOdxBNucuwLkfckJVE377uvwrf4+PYnw7z7kEPXl9djng8iiLjaMjgDlXXi2lmzIzaD4iq/NtasaZRAnCjB2td3VdX8BOOwgd18tR46hZQ+sbDXuwcHZy7pZmTSXqf6DOegIPZLzJ4H2Cqhusbd0zVqN/Wcx2enZTLblgNtP8ci8Z6mQthNFObIx2FZGXGFes50aMueHKD/IUFtm0up20wcQUEE5APl5vO9g+f5mE318y4Itx+gw32wd571arq9mq/g4FpeWp3z7Kxr4GJH8aKMR97NFTEpzgjJbg
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:mq_pass: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2021-08-23T15:21:15Z"
      name: korn-secrets-recv
      namespace: korn
    type: Opaque

